# Generated by Django 4.2.1 on 2023-05-13 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('TK', 'Tank'), ('HL', 'Healer'), ('DD', 'Damage dealer'), ('TR', 'Trader'), ('GM', 'Guild master'), ('QG', 'Quest giver'), ('WS', 'Warsmith'), ('TN', 'Tanner'), ('PM', 'Potion maker'), ('SM', 'Spell master')], default='TK', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.ads')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
