# Generated by Django 4.2.1 on 2023-05-16 12:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
