# Generated by Django 4.2.1 on 2023-05-21 18:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ads_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
